### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [jcreinhold/pyrobex#1]
## 🚀 Feature

Thanks for the great work! It would be really nice if this were available via conda-forge, as well.

## Motivation

Integrating with other packages that need conda-specific libraries would be easier.

## Pitch

I have a reasonable amount of experience dealing with conda recipes, so I can take care of it.

## Alternatives

N.A.

## Additional context

Already working on the recipe: https://github.com/conda-forge/staged-recipes/pull/15441

**Comment by sarthakpati** [comment]
This is merged and it will be availble in the conda channel soon. At that point, I will put in a PR to ensure it gets documented.

**Comment by jcreinhold** [comment]
Thank you!
