### ISSUE TITLE
robex function returns `Nonzero Return Code 126`

### ISSUE THREAD

**Issue by FloWPs** [jcreinhold/pyrobex#10]
## 🐛 Bug

I'm currently working on an MRI dataset (WMH) that requires the use of Robex for brain extraction and I found your package on Github !

Unfortunately, I tried installing the package using 3 different methods (_conda_, _pip_, and downloading package + running _python setup.py install_) but each time I run my code and the function robex() is called, it returns an error.

The output of the subprocess commmand in robex.py returns an error 126, for command found but not executable (very likely due to permission rights eventhough I executed chmod +x on all the folders, including the package itself).

## To Reproduce

1. Dowload package and run _python setup.py install_.
2. Download my code to reproduce the error with a single image : <https://github.com/FloWPs/ROBEX> 
3. Place yourself inside the ROBEX folder and run the command _python scripts/robex.py_

```
Traceback (most recent call last):
  File "/misc/raid/home/estermann/ROBEX/scripts/robex.py", line 40, in <module>
    stripped_t1, mask = robex(image_T1_pre)
  File "/home/estermann/.conda/envs/wmh/lib/python3.9/site-packages/pyrobex-0.4.2-py3.9.egg/pyrobex/robex.py", line 125, in robex
    raise PyRobexError(msg)
pyrobex.errors.PyRobexError: Nonzero return code 126.
ROBEX Output:
b''
```

## Expected behavior

If everything's fine, the message `[INFO] Brains extracted with success.` should be printed and 2 files saved at the _.npy_ format inside the data/robex_data folder.

## Environment

 - pyrobex version (e.g., 0.1.14): __0.4.2__
 - numpy and nibabel/antspy version: Numpy __1.23.3__ Nibabel __4.0.2__ (antspy not installed)
 - OS (e.g., Linux): __Linux__
 - How you installed pyrobex (e.g., `pip` or source): __Source__
 - Build command you used (if installed from source): __python setup.py install__
 - Python version: __3.9__
 - Any other relevant information: 

## Additional context

I tried to run _chmod +_ on runRobex.sh and on different folders when the problem first occured, but it didn't solve the issue.

**Comment by jcreinhold** [comment]
I should be able to look at this later. Can you try installing it with Python v3.8 or v3.7? This might be a version issue.

**Comment by jcreinhold** [comment]
Can you report where your `bash` is, i.e., the output of `which bash`?

**Comment by jcreinhold** [comment]
I don't think Python v3.9 is the problem; I suspect you're seeing the permission error due to `runROBEX.sh` (the script that `pyrobex` calls) trying to use `/bin/bash` instead of whatever `bash` you have permission to run.

Try re-installing the package with pip in a fresh Python environment, verify that you downloaded v0.4.3, and try again. Let me know if the update fixes the problem. Regardless, please report the output of `which bash`.

You can verify that you installed v0.4.3 by opening the Python interpreter and running:
```python
import pyrobex
print(pyrobex.__version__)
```
which should output: `0.4.3` if you installed pyrobex v0.4.3.

**Comment by FloWPs** [comment]
Thank you very much, it worked ! 👏

I created a new environment with `Python 3.9` and installed `pyrobex 0.4.3` with `pip`.
The output of `which bash` was __/usr/bin/bash__, thanks for the quick fix !

I'm gonna try running the package `intensity_normalization` on my skull-stripped images (I saw you did a great job on that too!) 😊
